### PR TITLE
Add CI on travis

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
should we add auto deploy here? @tomaszdurka

**Comment by tomaszdurka** [comment]
Yes, same as in cm-janus.

**Comment by tomaszdurka** [comment]
Please also add testing codebase.

**Comment by vogdb** [comment]
@tomaszdurka please look

**Comment by tomaszdurka** [comment]
lgtm

**Comment by tomaszdurka** [comment]
Oh, why is it not running?

**Comment by vogdb** [comment]
not running what? codecov?

**Comment by tomaszdurka** [comment]
travis ci

**Comment by vogdb** [comment]
I didn't enable it in Travis panel. Now it is enabled.

**Pull request merged**
