### PR TITLE
Add logging

### PR DESCRIPTION
**Pull request by vogdb**
Add logging dependencies and interface.

https://github.com/cargomedia/guides/tree/master/logging

Similar implementation: https://github.com/cargomedia/cm-janus/blob/master/lib/logger.js

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by vogdb** [comment]
Also @tomaszdurka please tell me what do you think about such `Context` class as below. It introduces two types `data` and `environment`.
```js
/**
 * @param {String} namespace
 * @param {Object} [data] app level fields
 * @param {Object} [environment] first level fields like 'exception', `computerInfo`, `httpRequest`
 * @constructor
 */
function LogContext(namespace, data, environment) {
  this.namespace = namespace;
  this.fields = {};
  this.fields[namespace] = {};
  if (data) {
    this.extendData(data);
  }
  if (environment) {
    this.extendEnvironment(environment);
  }
}

LogContext.prototype.extendData = function(fields) {
  deepExtend(this.fields[this.namespace], fields);
  return this;
};

LogContext.prototype.extendEnvironment = function(fields) {
  deepExtend(this.fields, fields);
  return this;
};

LogContext.prototype.merge = function(context) {
  return this.extendEnvironment(context.fields);
};

LogContext.prototype.toHash = function() {
  return _.clone(this.fields);
};

LogContext.prototype.clone = function() {
  return new LogContext(this.fields);
};
```

We can even add setters for environment fields to emphasise their value:

```js
LogContext.prototype.setException = function(exception) {
  this.fields.exception = exception;
  return this;
};
```

**Comment by tomaszdurka** [comment]
Let's talk this over tomorrow.

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
lets' merge it, lgtm

**Comment by vogdb** [comment]
hm, ok.

**Pull request merged**
